# Generated by Django 2.2.1 on 2019-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='type_is_crypto',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
