# Generated by Django 2.2.1 on 2019-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0002_currency_type_is_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickersymbol',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cryptodata.Exchange'),
            preserve_default=False,
        ),
    ]
