# Generated by Django 2.2.1 on 2019-05-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0003_tickersymbol_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptodata.Exchange'),
        ),
    ]
