# Generated by Django 2.2.1 on 2019-05-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0004_auto_20190505_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickersymbol',
            name='exchange',
        ),
        migrations.CreateModel(
            name='CurrencyExchangePK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=63)),
                ('key_type', models.CharField(choices=[('STR', 'string'), ('INT', 'integer')], default='STR', max_length=3)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodata.Currency')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodata.Exchange')),
            ],
        ),
    ]
