# Generated by Django 2.2.1 on 2019-05-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0005_auto_20190505_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='currencyexchangepk',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tickersymbol',
            options={'ordering': ['symbol']},
        ),
        migrations.RemoveField(
            model_name='currency',
            name='type_is_crypto',
        ),
    ]
