# Generated by Django 2.2.1 on 2019-05-08 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0006_auto_20190507_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency1', to='cryptodata.Currency')),
                ('currency2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency2', to='cryptodata.Currency')),
                ('exchanges', models.ManyToManyField(to='cryptodata.Exchange')),
            ],
        ),
        migrations.CreateModel(
            name='TradingPairExchangePK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=63)),
                ('key_type', models.CharField(choices=[('STR', 'string'), ('INT', 'integer')], default='STR', max_length=3)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodata.Exchange')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptodata.TradingPair')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
