# Generated by Django 2.2.1 on 2019-05-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0007_tradingpair_tradingpairexchangepk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchangepk',
            unique_together={('exchange', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='tickersymbol',
            unique_together={('currency', 'symbol')},
        ),
    ]
