# Generated by Django 2.2.1 on 2019-05-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0008_auto_20190509_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickersymbol',
            name='symbol',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tickersymbol',
            unique_together=set(),
        ),
    ]
