# Generated by Django 2.2.1 on 2019-05-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0011_auto_20190510_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='ticker_symbol',
            field=models.CharField(default='aaa', max_length=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TickerSymbol',
        ),
    ]
