# Generated by Django 2.2.1 on 2019-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptodata', '0012_auto_20190511_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('name', 'ticker_symbol')},
        ),
    ]
